### ISSUE TITLE
The option columns do not work

### ISSUE THREAD

**Issue by tomasrudh** [ljmerza/waze-card#6]
I have added a Columns option but I can't get it to work:
```
entities:
  - entity: sensor.waze_travel_time
    name: Arbete
    columns:
      - distance
      - duration
      - route
```
I have also tried this way:
```
entities:
  - entity: sensor.waze_travel_time
    name: Arbete
    columns: distance, duration, route
```
The column 'Name' is still shown.
